{
 "title": "otel-host_metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"otel-windows\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{job=\"otel-windows\", state=\"used\", instance=\"$host\"}"
    },
    {}
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum( system_cpu_time) by (cpu))"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(system_cpu_time{instance=\"$host\"}) by (cpu))) - avg(sum by (mode)(rate(system_cpu_time{state='idle',instance=\"$host\"}[$__rate_interval])))) * 100) / count(count(system_cpu_time{instance=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_memory_usage{instance=\"$host\",state=\"used\"})/(sum(system_memory_usage{instance=\"$host\"}))*100"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rate(system_cpu_time{instance=~\"$host\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{job=\"otel-windows\",instance=~\"$host\",state=\"used\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_usage{job=\"otel-windows\",instance=~\"$host\",state=\"free\"} ",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "disk activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_io{direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}}  Write"
    },
    {
     "expr": "-rate(system_disk_io{direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}}  Read"
    }
   ]
  },
  {
   "title": "Total Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_network_io{instance=\"$host\",device=\"Ethernet 4\"}[$__rate_interval])",
     "legendFormat": "Ethernet {{direction}}"
    },
    {
     "expr": "rate(system_network_io{instance=\"$host\",device=\"vEthernet (WSL)\"}[$__rate_interval])",
     "legendFormat": "WSL {{direction}}"
    },
    {
     "expr": "rate(system_network_io{instance=\"$host\",device=\"vEthernet (Default Switch)\"}[$__rate_interval])",
     "legendFormat": "Virtual Network {{direction}}"
    }
   ]
  },
  {
   "title": "TCP Socket Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"LISTEN\"}",
     "legendFormat": "Listening Sockets"
    },
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"ESTABLISHED\"}",
     "legendFormat": "Established Sockets"
    },
    {
     "expr": "sum(system_network_connections{instance=\"$host\",state!~\"ESTABLISHED|LISTEN\"})",
     "legendFormat": "Disconnecting Sockets"
    },
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"CLOSED\"}",
     "legendFormat": "Closed Sockets"
    }
   ]
  }
 ]
}