{
 "title": "otel-host_metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(system_cpu_time,job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "up time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max_over_time(timestamp(changes(up{instance=\"$host\"}[5m]) > 0)[24h:1m])"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(system_cpu_time{instance=\"$host\"}) by (cpu))) - avg(sum by (mode)(rate(system_cpu_time{state='idle',instance=\"$host\"}[$__rate_interval])))) * 100) / count(count(system_cpu_time{instance=\"$host\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"used\", instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "File System Use",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_filesystem_usage{instance=\"$host\",state=\"used\"}) by (mountpoint) / sum(system_filesystem_usage{instance=\"$host\"}) by (mountpoint)",
     "legendFormat": "{{mountpoint}}"
    },
    {}
   ]
  },
  {
   "title": "Bytes Transmit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(system_network_packets{instance=\"$host\",direction=\"transmit\"}[24h]))"
    }
   ]
  },
  {
   "title": "Bytes Recieved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(system_network_packets{instance=\"$host\",direction=\"receive\"}[24h]))"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum( system_cpu_time) by (cpu))"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rate(system_cpu_time{instance=~\"$host\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"used\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"free\"} ",
     "legendFormat": "free"
    },
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"buffered\"} ",
     "legendFormat": "Buffered"
    },
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"cached\"} ",
     "legendFormat": "Cached"
    },
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"slab_reclaimable\"} ",
     "legendFormat": "Reclaimable"
    },
    {
     "expr": "system_memory_usage{instance=~\"$host\",state=\"slab_unreclaimable\"} ",
     "legendFormat": "Unreclaimable"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(system_disk_io{instance=\"$host\",direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}}  Write"
    },
    {
     "expr": "-rate(system_disk_io{host=\"$host\",direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}}  Read"
    }
   ]
  },
  {
   "title": "Total Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "-rate(system_network_io{instance=\"$host\",direction=\"transmit\"}[$__rate_interval])",
     "legendFormat": "{{device}} transmit"
    },
    {
     "expr": "rate(system_network_io{instance=\"$host\",direction=\"receive\"}[$__rate_interval])",
     "legendFormat": "{{device}} recieve"
    }
   ]
  },
  { "title": "Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Weighted IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(system_disk_weighted_io_time{instance=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(system_disk_operations{instance=\"$host\",direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "-rate(system_disk_operations{instance=\"$host\",direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Disk Merged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(system_disk_merged{instance=\"$host\",direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "-rate(system_disk_merged{instance=\"$host\",direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "File System Inode Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_inodes_usage{instance=\"$host\",state=\"used\"}",
     "legendFormat": "Mount: {{mountpoint}}"
    },
    {
     "expr": "sum(system_filesystem_inodes_usage{instance=\"$host\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Disk Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(system_disk_operation_time{instance=\"$host\",direction=\"read\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "-rate(system_disk_operation_time{instance=\"$host\",direction=\"write\"}[$__rate_interval])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Harddrive useage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage{instance=\"$host\",state=\"used\"}",
     "legendFormat": "{{device}} used"
    }
   ]
  },
  {
   "title": "Disk Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "system_disk_pending_operations{instance=\"$host\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true
  },
  {
   "title": "TCP Socket Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"LISTEN\"}",
     "legendFormat": "Listening Sockets"
    },
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"ESTABLISHED\"}",
     "legendFormat": "Established Sockets"
    },
    {
     "expr": "sum(system_network_connections{instance=\"$host\",state!~\"ESTABLISHED|LISTEN\"})",
     "legendFormat": "Disconnecting Sockets"
    },
    {
     "expr": "system_network_connections{instance=\"$host\",state=\"CLOSED\"}",
     "legendFormat": "Closed Sockets"
    }
   ]
  }
 ]
}