receivers:
  hostmetrics:
  
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
        #interfaces: ["vEthernet (WSL)", "Ethernet 4","vEthernet (Default Switch)"]

      process:
      #  include:
      #    names: ["otelcol.exe"]
exporters:
  prometheus:
    endpoint: "0.0.0.0:9101"
    const_labels:
      label1: otel-windows
  logging:
 
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
  batch:
  batch/2:
    send_batch_size: 10000
    timeout: 10s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter,batch]
      exporters: [prometheus,logging]
